# Generated by Django 2.0.2 on 2018-10-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
