# Generated by Django 2.0.2 on 2018-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_auto_20181010_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='id',
        ),
        migrations.AddField(
            model_name='fund',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
