# Generated by Django 2.0.2 on 2018-10-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_auto_20181010_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='fund',
            new_name='f_id',
        ),
        migrations.AddField(
            model_name='fund',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='number',
            field=models.IntegerField(),
        ),
    ]
