# Generated by Django 2.0.2 on 2018-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_remove_expense_f_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
