# Generated by Django 2.0.2 on 2018-10-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0006_auto_20181010_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='number',
        ),
        migrations.AddField(
            model_name='expense',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fund.Fund'),
            preserve_default=False,
        ),
    ]
