# Generated by Django 2.0.2 on 2018-10-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_auto_20181010_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'permissions': (('edit_own', 'Can Edit own property'),)},
        ),
    ]
