# Generated by Django 2.0.2 on 2018-10-27 13:32

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0010_auto_20181017_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='date_fa',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
    ]
