# Generated by Django 2.0.2 on 2018-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0011_fund_date_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
