# Generated by Django 2.0.2 on 2018-11-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0012_auto_20181105_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='summary',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
