# Generated by Django 2.0.2 on 2018-11-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0015_auto_20181113_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'permissions': (('view_fund', 'Can view funds'), ('index_fund', 'Can view list of funds'))},
        ),
    ]
