# Generated by Django 2.0.2 on 2018-09-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='prefactor/')),
                ('Summary', models.CharField(max_length=300)),
                ('PreFactor_Name', models.IntegerField()),
            ],
        ),
    ]
