# Generated by Django 2.0.2 on 2018-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefactor', '0002_auto_20180914_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefactor',
            name='Summary',
            field=models.TextField(max_length=600),
        ),
    ]
