# Generated by Django 2.0.2 on 2018-10-26 18:40

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_date2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date2',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
