# Generated by Django 2.0.2 on 2018-10-27 08:35

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20181027_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date2',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
    ]
