# Generated by Django 2.0.2 on 2018-11-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20181103_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
