# Generated by Django 2.0.2 on 2019-06-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
