# Generated by Django 2.0.2 on 2019-06-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
