# Generated by Django 2.0.2 on 2018-11-04 07:29

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20181104_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.IntegerField(default=customer.models.default_customer_code, unique=True),
        ),
    ]
