# Generated by Django 2.0.2 on 2018-11-04 07:32

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20181104_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.IntegerField(blank=True, default=customer.models.default_customer_code, unique=True),
        ),
    ]
