# Generated by Django 2.0.2 on 2018-11-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20181104_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='No Address', max_length=600),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
