# Generated by Django 2.0.2 on 2018-12-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20181201_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='representator',
            new_name='agent',
        ),
    ]
