# Generated by Django 2.0.2 on 2018-12-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20181208_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agent',
            field=models.BooleanField(default=False),
        ),
    ]
