# Generated by Django 2.0.2 on 2018-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20181208_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
