# Generated by Django 2.0.2 on 2018-12-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20181218_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='code',
        ),
        migrations.RemoveField(
            model_name='type',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
