# Generated by Django 2.0.2 on 2019-01-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReqEntered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_entered', models.CharField(max_length=7)),
                ('number_automation', models.IntegerField()),
                ('started', models.BooleanField(default=False)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='req_track.ReceivedBy')),
            ],
        ),
    ]
