# Generated by Django 2.0.2 on 2019-08-10 10:36

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(blank=True, max_length=60, null=True)),
                ('addr', models.TextField(blank=True, null=True)),
                ('entered', models.BooleanField(default=False)),
                ('exported', models.BooleanField(default=False)),
                ('temp_code', models.CharField(default=None, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerResolver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1', models.CharField(max_length=12)),
                ('code2', models.CharField(max_length=12)),
                ('similarity', models.FloatField()),
                ('resolved', models.BooleanField(default=False)),
                ('cleared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('prof_number', models.CharField(max_length=40)),
                ('date_txt', models.CharField(blank=True, max_length=12, null=True)),
                ('date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=10)),
                ('is_entered', models.BooleanField(default=False)),
                ('red_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_number', models.IntegerField()),
                ('perm_number', models.IntegerField()),
                ('perm_date', models.CharField(max_length=12)),
                ('customer_code', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('product_code', models.IntegerField()),
                ('product_details', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('qty', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('extra', models.FloatField(null=True)),
                ('payable', models.FloatField(null=True)),
                ('kw', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProformaFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=15)),
                ('details', models.TextField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReqEntered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_entered', models.CharField(blank=True, max_length=20, null=True)),
                ('number_automation', models.IntegerField(unique=True)),
                ('is_entered', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_text', models.CharField(default='الوند', max_length=40)),
                ('date_txt', models.CharField(blank=True, max_length=12, null=True)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('is_request', models.BooleanField(default=True)),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackItemsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('kw', models.CharField(blank=True, max_length=50, null=True)),
                ('frame_size', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('ic', models.CharField(blank=True, max_length=50, null=True)),
                ('im', models.CharField(blank=True, max_length=50, null=True)),
                ('yd', models.CharField(blank=True, max_length=50, null=True)),
                ('efficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('pf', models.CharField(blank=True, max_length=50, null=True)),
                ('current_ln', models.CharField(blank=True, max_length=50, null=True)),
                ('current_ls_to_ln', models.CharField(blank=True, max_length=50, null=True)),
                ('torque_tn', models.CharField(blank=True, max_length=50, null=True)),
                ('torque_ts_to_tn', models.CharField(blank=True, max_length=50, null=True)),
                ('torque_tmax_to_tn', models.CharField(blank=True, max_length=50, null=True)),
                ('torque_rotor_inertia', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('freq', models.IntegerField(default=50)),
                ('details', models.TextField()),
                ('red_flag', models.BooleanField(default=False)),
                ('green_flag', models.BooleanField(default=False)),
                ('is_entered', models.BooleanField(default=False)),
                ('temp_str', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackXpref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('customer_code', models.BigIntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=60, null=True)),
                ('date_fa', models.CharField(max_length=15)),
                ('exp_date_fa', models.CharField(blank=True, max_length=15, null=True)),
                ('code', models.CharField(max_length=40)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('req_number', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_reduction', models.FloatField(blank=True, null=True)),
                ('perm_number', models.CharField(blank=True, max_length=10, null=True)),
                ('receivable', models.FloatField(blank=True, null=True)),
                ('red_flag', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('is_entered', models.BooleanField(default=False)),
            ],
        ),
    ]
