# Generated by Django 2.0.2 on 2019-04-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('prof_number', models.IntegerField()),
                ('date_txt', models.CharField(blank=True, max_length=12, null=True)),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
