# Generated by Django 2.0.2 on 2019-01-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0002_reqentered_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqentered',
            name='number_automation',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='reqentered',
            name='number_entered',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
