# Generated by Django 2.0.2 on 2019-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='prof_number',
            field=models.CharField(max_length=12),
        ),
    ]
