# Generated by Django 2.0.2 on 2019-09-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0002_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='entered',
            field=models.BooleanField(default=False),
        ),
    ]
