# Generated by Django 2.0.2 on 2019-04-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0003_auto_20190414_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='prof_number',
            field=models.CharField(max_length=40),
        ),
    ]
