# Generated by Django 2.0.2 on 2019-01-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0003_auto_20190120_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqentered',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='reqentered',
            name='received_by',
        ),
        migrations.AddField(
            model_name='reqentered',
            name='owner_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ReceivedBy',
        ),
    ]
