# Generated by Django 2.0.2 on 2019-10-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0003_pricelist_entered'),
    ]

    operations = [
        migrations.CreateModel(
            name='TadvinTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('doctype_code', models.IntegerField()),
                ('doctype', models.CharField(max_length=20)),
                ('doc_number', models.IntegerField()),
                ('row_number', models.IntegerField()),
                ('date', models.CharField(max_length=14)),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=150, null=True)),
                ('prof_number', models.IntegerField()),
                ('prof_row', models.IntegerField()),
                ('perm_number', models.PositiveIntegerField(blank=True, null=True)),
                ('perm_row', models.PositiveIntegerField(blank=True, null=True)),
                ('havale_number', models.PositiveIntegerField(blank=True, null=True)),
                ('havale_row', models.PositiveIntegerField(blank=True, null=True)),
                ('factor_number', models.PositiveIntegerField(blank=True, null=True)),
                ('factor_row', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.IntegerField()),
                ('discount_value', models.FloatField(blank=True, null=True)),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('price_unit', models.FloatField()),
                ('price', models.FloatField()),
                ('entered', models.BooleanField(default=False)),
            ],
        ),
    ]
