# Generated by Django 2.0.2 on 2019-01-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0004_auto_20190121_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqentered',
            name='attachment',
            field=models.CharField(default='ندارد', max_length=100),
        ),
        migrations.AddField(
            model_name='reqentered',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reqentered',
            name='date_txt',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='reqentered',
            name='is_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reqentered',
            name='owner_text',
            field=models.CharField(default='الوند', max_length=20),
        ),
    ]
