# Generated by Django 2.0.2 on 2019-04-14 10:27

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0005_auto_20190414_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
