# Generated by Django 2.0.2 on 2019-01-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0005_auto_20190121_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqentered',
            name='attachment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
