# Generated by Django 2.0.2 on 2019-01-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0006_auto_20190121_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqentered',
            name='number_entered',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
