# Generated by Django 2.0.2 on 2019-04-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0006_payments_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackItemsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackXpref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('number', models.IntegerField(unique=True)),
                ('req_number', models.CharField(max_length=40)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('date_fa', models.CharField(max_length=15)),
                ('exp_date_fa', models.CharField(blank=True, max_length=15, null=True)),
                ('perm_number', models.CharField(blank=True, max_length=10, null=True)),
                ('red_flag', models.BooleanField(default=False)),
                ('is_entered', models.BooleanField(default=False)),
            ],
        ),
    ]
