# Generated by Django 2.0.2 on 2019-01-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0007_auto_20190121_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqentered',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
