# Generated by Django 2.0.2 on 2019-04-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0007_trackitemscode_trackxpref'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackitemscode',
            name='current_ln',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='current_ls_to_ln',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='frame_size',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='freq',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='ic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='im',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='ip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='kw',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='pf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='torque_rotor_inertia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='torque_tmax_to_tn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='torque_tn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='torque_ts_to_tn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='voltage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='yd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
