# Generated by Django 2.0.2 on 2019-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0008_reqentered_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqentered',
            name='owner_text',
            field=models.CharField(default='الوند', max_length=40),
        ),
    ]
