# Generated by Django 2.0.2 on 2019-01-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0009_auto_20190121_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqentered',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
