# Generated by Django 2.0.2 on 2019-04-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0009_auto_20190415_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackxpref',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackxpref',
            name='price_reduction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackxpref',
            name='receivable',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
