# Generated by Django 2.0.2 on 2019-01-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0010_reqentered_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqentered',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
