# Generated by Django 2.0.2 on 2019-04-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0010_auto_20190415_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackxpref',
            name='green_flag',
            field=models.BooleanField(default=False),
        ),
    ]
