# Generated by Django 2.0.2 on 2019-01-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0011_auto_20190121_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqentered',
            old_name='started',
            new_name='is_entered',
        ),
    ]
