# Generated by Django 2.0.2 on 2019-04-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0011_trackxpref_green_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackxpref',
            name='green_flag',
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='green_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='is_entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackitemscode',
            name='red_flag',
            field=models.BooleanField(default=False),
        ),
    ]
