# Generated by Django 2.0.2 on 2019-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0012_auto_20190415_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackxpref',
            name='customer_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackxpref',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trackxpref',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
