# Generated by Django 2.0.2 on 2019-04-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0013_auto_20190415_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackxpref',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackxpref',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackxpref',
            name='req_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
