# Generated by Django 2.0.2 on 2019-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0014_auto_20190415_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackxpref',
            name='receivable',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
