# Generated by Django 2.0.2 on 2019-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0015_auto_20190415_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackxpref',
            name='customer_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
