# Generated by Django 2.0.2 on 2019-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0016_auto_20190415_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackxpref',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
