# Generated by Django 2.0.2 on 2019-04-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0018_auto_20190415_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackxpref',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
