# Generated by Django 2.0.2 on 2019-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0019_trackxpref_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackitemscode',
            name='temp_str',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
