# Generated by Django 2.0.2 on 2019-06-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0022_proformafollowup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=60)),
                ('addr', models.TextField()),
                ('entered', models.BooleanField(default=False)),
            ],
        ),
    ]
