# Generated by Django 2.0.2 on 2019-06-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0024_auto_20190612_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='temp_code',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
