# Generated by Django 2.0.2 on 2019-06-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0025_customer_temp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerResolver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1', models.CharField(max_length=12)),
                ('code2', models.CharField(max_length=12)),
                ('similarity', models.FloatField()),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
