# Generated by Django 2.0.2 on 2019-06-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0026_customerresolver'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresolver',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
