# Generated by Django 2.0.2 on 2019-06-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0027_customerresolver_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='exported',
            field=models.BooleanField(default=False),
        ),
    ]
