# Generated by Django 2.0.2 on 2019-07-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0028_customer_exported'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_number', models.IntegerField()),
                ('perm_number', models.IntegerField()),
                ('perm_date', models.CharField(max_length=12)),
                ('customer_code', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('product_code', models.IntegerField()),
                ('product_details', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('qty', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('extra', models.FloatField(null=True)),
                ('payable', models.FloatField(null=True)),
                ('kw', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
