# Generated by Django 2.0.2 on 2020-01-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerow',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
