# Generated by Django 2.0.2 on 2019-01-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
        ('customer', '0001_initial'),
        ('fund', '0001_initial'),
        ('admin', '0001_initial'),
        ('accounts', '0002_customeruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
