# Generated by Django 2.0.2 on 2019-01-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sales_exp',
            field=models.BooleanField(default=False),
        ),
    ]
