# Generated by Django 2.0.2 on 2018-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrefactorVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_ver_id', models.IntegerField()),
                ('PreFactor_Id', models.IntegerField()),
                ('pref_ver_Image', models.ImageField(upload_to='pref_verification/')),
                ('pref_summary', models.TextField(max_length=600)),
            ],
        ),
    ]
