# Generated by Django 2.0.2 on 2020-01-26 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0040_reqpart_services_wastage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(unique=True)),
                ('amount', models.FloatField()),
                ('date_fa', django_jalali.db.models.jDateField(default=django.utils.timezone.now)),
                ('due_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, max_length=600, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='request.PaymentType')),
            ],
            options={
                'permissions': (('read_payment', 'Can read payment details'), ('index_payment', 'Can see list of payments')),
            },
        ),
        migrations.CreateModel(
            name='IncomeRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_fa', django_jalali.db.models.jDateField(default=django.utils.timezone.now)),
                ('summary', models.TextField(blank=True, max_length=600, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('perm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Perm')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Xpref')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
