# Generated by Django 2.0.2 on 2020-01-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_incomerow_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerow',
            name='income',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incomes.Income'),
            preserve_default=False,
        ),
    ]
