# Generated by Django 2.0.2 on 2018-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motors',
            name='PF',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='current_ln',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='current_ls_to_ln',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='efficiency',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='ex_type',
            field=models.IntegerField(choices=[(0, 'safe'), (1, 'Exn'), (2, 'ExnA'), (3, 'Exe'), (4, 'Exd'), (5, 'Exde'), (6, 'other types')], default=0),
        ),
        migrations.AddField(
            model_name='motors',
            name='frame_size',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='freq',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='motors',
            name='ic',
            field=models.IntegerField(choices=[(0, 'IC411'), (1, 'IC511'), (2, 'IC611')], default=0),
        ),
        migrations.AddField(
            model_name='motors',
            name='im',
            field=models.IntegerField(choices=[(0, 'IMB3'), (1, 'IMB35')], default=0),
        ),
        migrations.AddField(
            model_name='motors',
            name='images',
            field=models.FileField(default=1, upload_to='motordb/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='ip',
            field=models.IntegerField(choices=[(0, 'IP55'), (1, 'IP65'), (2, 'IP23'), (3, 'Other')], default=0),
        ),
        migrations.AddField(
            model_name='motors',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='motors',
            name='torque_rotor_inertia',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='torque_tmax_to_tn',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='torque_tn',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='torque_ts_to_tn',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='voltage',
            field=models.IntegerField(choices=[(0, '380'), (1, '400'), (2, '3000'), (3, '3300'), (4, '6000'), (5, '6600')], default=0),
        ),
        migrations.AddField(
            model_name='motors',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motors',
            name='kw',
            field=models.FloatField(choices=[(0, '5.5 kw'), (1, '7.5 kw'), (2, '11 kw'), (3, '15 kw'), (4, '18.5 kw'), (5, '22 kw'), (6, '30 kw'), (7, '37 kw'), (8, '45 kw'), (9, '55 kw'), (10, '75 kw'), (11, '90 kw'), (12, '110 kw'), (13, '132 kw'), (14, '160 kw'), (15, '185 kw'), (16, '200 kw'), (17, '220 kw'), (18, '250 kw'), (19, '315 kw'), (20, '355 kw'), (21, '400 kw'), (22, '450 kw')], default=7),
        ),
        migrations.AlterField(
            model_name='motors',
            name='speed',
            field=models.IntegerField(choices=[(0, '1000 RPM'), (1, '1500 RPM'), (2, '3000 RPM')], default=1),
        ),
    ]
