# Generated by Django 2.0.2 on 2018-10-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0002_auto_20181018_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motors',
            name='images',
        ),
    ]
