# Generated by Django 2.0.2 on 2019-08-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0002_auto_20190824_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorscode',
            options={'permissions': (('index_motorscode', 'can view motor codes'),)},
        ),
    ]
