# Generated by Django 2.0.2 on 2018-10-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0004_auto_20181018_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motors',
            name='im',
            field=models.CharField(choices=[('IMB3', 'IMB3'), ('IMB35', 'IMB35')], default='IMB3', max_length=6),
        ),
    ]
