# Generated by Django 2.0.2 on 2019-12-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0004_motorscode_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorscode',
            name='label',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
