# Generated by Django 2.0.2 on 2018-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0005_auto_20181018_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motors',
            name='kw',
            field=models.FloatField(choices=[(0, '5.5 kw'), (7.5, '7.5 kw'), (11, '11 kw'), (15, '15 kw'), (18.5, '18.5 kw'), (22, '22 kw'), (30, '30 kw'), (37, '37 kw'), (45, '45 kw'), (55, '55 kw'), (75, '75 kw'), (90, '90 kw'), (110, '110 kw'), (132, '132 kw'), (160, '160 kw'), (185, '185 kw'), (200, '200 kw'), (220, '220 kw'), (250, '250 kw'), (315, '315 kw'), (355, '355 kw'), (400, '400 kw'), (450, '450 kw')], default=5.5),
        ),
    ]
