# Generated by Django 2.0.2 on 2019-12-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0005_motorscode_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorscode',
            name='yd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
