# Generated by Django 2.0.2 on 2018-10-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0007_auto_20181018_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motors',
            name='ex_type',
            field=models.IntegerField(choices=[(0, 'safe'), (1, 'Exn'), (2, 'ExnA'), (3, 'Exe'), (4, 'Exd'), (5, 'Exde'), (6, 'other types')], default=0),
        ),
        migrations.AlterField(
            model_name='motors',
            name='ic',
            field=models.IntegerField(choices=[(0, 'IC411'), (1, 'IC511'), (2, 'IC611')], default=0),
        ),
        migrations.AlterField(
            model_name='motors',
            name='im',
            field=models.IntegerField(choices=[(0, 'IMB3'), (1, 'IMB35')], default=0),
        ),
        migrations.AlterField(
            model_name='motors',
            name='ip',
            field=models.IntegerField(choices=[(0, 'IP55'), (1, 'IP65'), (2, 'IP23'), (3, 'Other')], default=0),
        ),
    ]
