# Generated by Django 2.0.2 on 2019-04-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0009_motorsprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorscode',
            name='ip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
