# Generated by Django 2.0.2 on 2019-05-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0011_motorscode_ie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorscode',
            name='ic',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
