# Generated by Django 2.0.2 on 2018-10-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0017_auto_20181024_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motors',
            name='ic',
            field=models.IntegerField(blank=True, choices=[(0, 'IC411'), (1, 'IC511'), (2, 'IC611')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='motors',
            name='ip',
            field=models.IntegerField(blank=True, choices=[(0, 'IP55'), (1, 'IP65'), (2, 'IP23'), (3, 'Other')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='motors',
            name='speed',
            field=models.IntegerField(blank=True, choices=[(3, '750 RPM'), (0, '1000 RPM'), (1, '1500 RPM'), (2, '3000 RPM')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='motors',
            name='voltage',
            field=models.IntegerField(blank=True, choices=[(0, '380'), (1, '400'), (2, '3000'), (3, '3300'), (4, '6000'), (5, '6600')], default=0, null=True),
        ),
    ]
