# Generated by Django 2.0.2 on 2018-11-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0018_auto_20181024_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motors',
            options={'permissions': (('view_motordb', 'can view motor database'), ('index_motordb', 'can view list of motor database'))},
        ),
    ]
