# Generated by Django 2.0.2 on 2019-08-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20190817_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reqspec',
            options={'permissions': (('index_reqspecs', 'can see list of request Specs'), ('read_reqspecs', 'can read request Specs'))},
        ),
    ]
