# Generated by Django 2.0.2 on 2019-08-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20190817_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xpref',
            options={'permissions': (('index_proforma', 'Can index Proforma'), ('index_xpref', 'Can index Proformas'), ('read_proforma', 'Can read Proforma'))},
        ),
    ]
