# Generated by Django 2.0.2 on 2019-08-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20190817_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefspec',
            options={'permissions': (('index_prefspec', 'can see list of prefsepcs'),)},
        ),
    ]
