# Generated by Django 2.0.2 on 2019-08-23 07:35

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_proformafollowup_xpref'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformafollowup',
            name='next_followup',
            field=django_jalali.db.models.jDateField(default=datetime.datetime(2019, 8, 30, 7, 35, 50, 861890, tzinfo=utc)),
        ),
    ]
