# Generated by Django 2.0.2 on 2019-08-23 08:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0009_proformafollowup_next_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformafollowup',
            name='author',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proformafollowup',
            name='next_followup',
            field=django_jalali.db.models.jDateField(default=datetime.datetime(2019, 8, 30, 8, 24, 47, 760583, tzinfo=utc)),
        ),
    ]
