# Generated by Django 2.0.2 on 2019-09-02 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_reqparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqparts',
            name='req',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='request.Requests'),
            preserve_default=False,
        ),
    ]
