# Generated by Django 2.0.2 on 2019-09-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_prefpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpref',
            name='due_date_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
