# Generated by Django 2.0.2 on 2019-10-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0021_xpref_due_date_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perm_prof', to='request.Xpref')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('row', models.IntegerField()),
                ('code', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('price_unit', models.FloatField()),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permspec_perm', to='request.Perm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
