# Generated by Django 2.0.2 on 2019-10-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0027_auto_20191014_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespec',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
