# Generated by Django 2.0.2 on 2019-10-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0028_auto_20191014_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryoutspec',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoicespec',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
