# Generated by Django 2.0.2 on 2019-11-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0031_xpref_date_fa_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_fa_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perm',
            name='date_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='date_fa_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
