# Generated by Django 2.0.2 on 2019-11-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0032_auto_20191112_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perm',
            name='date_text',
        ),
    ]
