# Generated by Django 2.0.2 on 2020-07-25 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0043_profchangerequest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='date_fa_raw',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
