# Generated by Django 2.0.2 on 2020-07-28 13:11

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('req_track', '0004_tadvintotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqentered',
            name='date_fa',
            field=django_jalali.db.models.jDateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
