# Generated by Django 2.0.2 on 2018-09-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='requests/prefactors/original/')),
                ('summary', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PrefactorVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='requests/prefactors/verifications/')),
                ('summary', models.TextField(max_length=1000)),
                ('pref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Prefactor')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='requests/')),
                ('summary', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='prefactor',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Requests'),
        ),
    ]
