# Generated by Django 2.0.2 on 2018-09-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
