# Generated by Django 2.0.2 on 2018-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_requests_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefactor',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prefactorverification',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
