# Generated by Django 2.0.2 on 2018-09-18 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20180918_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefactor',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='prefactorverification',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='requests',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
