# Generated by Django 2.0.2 on 2018-09-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20180918_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='kw',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='rpm',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
