# Generated by Django 2.0.2 on 2019-08-23 07:19

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20190818_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaFollowUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fa', django_jalali.db.models.jDateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
