# Generated by Django 2.0.2 on 2018-09-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20180927_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.FloatField()),
                ('rpm', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='requests',
            name='kw',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='rpm',
        ),
        migrations.AlterField(
            model_name='requests',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='requests/'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reqspec',
            name='req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Requests'),
        ),
    ]
