# Generated by Django 2.0.2 on 2018-09-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20180928_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqspec',
            name='ic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqspec',
            name='ip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqspec',
            name='voltage',
            field=models.IntegerField(default=380),
        ),
    ]
