# Generated by Django 2.0.2 on 2019-08-23 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_proformafollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformafollowup',
            name='xpref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='request.Xpref'),
            preserve_default=False,
        ),
    ]
