# Generated by Django 2.0.2 on 2018-09-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20180928_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqspec',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
