# Generated by Django 2.0.2 on 2018-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_reqspec_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqspec',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
