# Generated by Django 2.0.2 on 2019-08-23 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_auto_20190823_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformafollowup',
            name='next_followup',
            field=django_jalali.db.models.jDateField(default=datetime.datetime(2019, 8, 30, 15, 24, 56, 713161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reqspec',
            name='rpm',
            field=models.IntegerField(null=True),
        ),
    ]
