# Generated by Django 2.0.2 on 2018-09-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_reqspec_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqspec',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqspec',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
