# Generated by Django 2.0.2 on 2019-08-24 18:12

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_auto_20190823_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xpref',
            name='number_auto',
        ),
        migrations.RemoveField(
            model_name='xpref',
            name='temp_number',
        ),
        migrations.AlterField(
            model_name='proformafollowup',
            name='next_followup',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reqspec',
            name='rpm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
