# Generated by Django 2.0.2 on 2018-10-03 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_auto_20180930_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('image', models.ImageField(upload_to='', verbose_name='request/payments/')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField(blank=True, max_length=600, null=True)),
                ('xpref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Xpref')),
            ],
        ),
    ]
