# Generated by Django 2.0.2 on 2018-10-04 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_requests_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='XprefVerf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='', verbose_name='requests/views/verifications/')),
                ('summary', models.TextField(max_length=1000)),
                ('xpref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Xpref')),
            ],
        ),
    ]
