# Generated by Django 2.0.2 on 2019-03-11 06:27

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_requests_date_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpref',
            name='du_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xpref',
            name='perm',
            field=models.BooleanField(default=False),
        ),
    ]
