# Generated by Django 2.0.2 on 2019-09-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_auto_20190902_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqpart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
