# Generated by Django 2.0.2 on 2019-03-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_auto_20190311_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xpref',
            old_name='du_date',
            new_name='due_date',
        ),
    ]
