# Generated by Django 2.0.2 on 2019-03-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_auto_20190311_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefspec',
            name='reqspec_eq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='request.ReqSpec'),
            preserve_default=False,
        ),
    ]
