# Generated by Django 2.0.2 on 2018-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_requests_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='requests/requests/'),
        ),
    ]
