# Generated by Django 2.0.2 on 2018-10-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_auto_20181017_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='requests/'),
        ),
    ]
