# Generated by Django 2.0.2 on 2019-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_prefspec_reqspec_eq'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefspec',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
