# Generated by Django 2.0.2 on 2019-09-03 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0019_reqpart_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('reqpart_eq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.ReqPart')),
                ('xpref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Xpref')),
            ],
        ),
    ]
