# Generated by Django 2.0.2 on 2018-10-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_auto_20181017_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqspec',
            name='images',
            field=models.FileField(default=1, upload_to='specs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(default='payments/default.jpg', upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='prefactor',
            name='image',
            field=models.ImageField(upload_to='prefactors'),
        ),
        migrations.AlterField(
            model_name='prefactorverification',
            name='image',
            field=models.ImageField(upload_to='pref_verifications'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='requests/'),
        ),
        migrations.AlterField(
            model_name='xpref',
            name='image',
            field=models.ImageField(upload_to='prefactors/'),
        ),
        migrations.AlterField(
            model_name='xprefverf',
            name='image',
            field=models.ImageField(upload_to='verifications/'),
        ),
    ]
