# Generated by Django 2.0.2 on 2019-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_prefspec_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefspec',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reqspec',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
