# Generated by Django 2.0.2 on 2019-03-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0021_auto_20190316_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='proforma',
        ),
        migrations.RemoveField(
            model_name='prefactor',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='prefactor',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='prefactorverification',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='prefactorverification',
            name='pref_id',
        ),
        migrations.RemoveField(
            model_name='xprefverf',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='xprefverf',
            name='xpref',
        ),
        migrations.AlterField(
            model_name='prefspec',
            name='xpref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Xpref'),
        ),
        migrations.AlterField(
            model_name='reqspec',
            name='req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Requests'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Prefactor',
        ),
        migrations.DeleteModel(
            name='PrefactorVerification',
        ),
        migrations.DeleteModel(
            name='XprefVerf',
        ),
    ]
