# Generated by Django 2.0.2 on 2018-10-27 08:50

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0022_auto_20181024_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='date_fa',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
    ]
