# Generated by Django 2.0.2 on 2019-10-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0022_perm_permspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_out_perm', to='request.Perm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryOutSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('row', models.IntegerField()),
                ('code', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('serial_number', models.CharField(max_length=20)),
                ('price_unit', models.FloatField()),
                ('invout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.InventoryOut')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('invout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_invout', to='request.Perm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('row', models.IntegerField()),
                ('code', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('serial_number', models.CharField(max_length=20)),
                ('price_unit', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
