# Generated by Django 2.0.2 on 2019-04-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0023_prefspec_qty_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefspec',
            name='qty_sent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
