# Generated by Django 2.0.2 on 2019-10-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0023_inventoryout_inventoryoutspec_invoice_invoicespec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_invout', to='request.InventoryOut'),
        ),
    ]
