# Generated by Django 2.0.2 on 2018-10-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0023_requests_date_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqspec',
            name='owner',
        ),
    ]
