# Generated by Django 2.0.2 on 2019-04-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0024_auto_20190413_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpref',
            name='perm_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
