# Generated by Django 2.0.2 on 2019-04-14 06:15

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0025_xpref_perm_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpref',
            name='perm_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
