# Generated by Django 2.0.2 on 2019-10-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0025_perm_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoutspec',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicespec',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permspec',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
