# Generated by Django 2.0.2 on 2019-04-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0027_auto_20190414_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefspec',
            name='qty_sent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
