# Generated by Django 2.0.2 on 2018-10-27 12:42

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0028_payment_date_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_fa',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
    ]
