# Generated by Django 2.0.2 on 2018-11-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0029_auto_20181027_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'permissions': (('index_requests', 'can see list of requests'), ('read_requests', 'can read requests'))},
        ),
    ]
