# Generated by Django 2.0.2 on 2019-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0029_auto_20190414_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqspec',
            name='code',
            field=models.BigIntegerField(default=99009900),
        ),
    ]
