# Generated by Django 2.0.2 on 2018-11-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0030_auto_20181101_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefactor',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
