# Generated by Django 2.0.2 on 2019-04-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0030_reqspec_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqspec',
            old_name='ic',
            new_name='ic_type',
        ),
        migrations.RenameField(
            model_name='reqspec',
            old_name='ip',
            new_name='ip_type',
        ),
    ]
