# Generated by Django 2.0.2 on 2018-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0031_auto_20181105_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqspec',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='specs/'),
        ),
    ]
