# Generated by Django 2.0.2 on 2019-04-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0032_auto_20190417_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ictype',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='iptype',
            name='summary',
        ),
    ]
