# Generated by Django 2.0.2 on 2018-11-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0032_auto_20181105_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpref',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prefactors/'),
        ),
    ]
