# Generated by Django 2.0.2 on 2018-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0033_auto_20181105_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='xpref',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
