# Generated by Django 2.0.2 on 2019-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0033_remove_perm_date_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date_fa_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
