# Generated by Django 2.0.2 on 2019-11-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0034_payment_due_date_fa_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='due_date_fa_text',
            new_name='due_date_text',
        ),
    ]
