# Generated by Django 2.0.2 on 2019-04-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0034_auto_20190417_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefspec',
            old_name='ic',
            new_name='ic_type',
        ),
        migrations.RenameField(
            model_name='prefspec',
            old_name='ip',
            new_name='ip_type',
        ),
    ]
