# Generated by Django 2.0.2 on 2018-11-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0035_xpref_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xpref',
            options={'permissions': (('index_proforma', 'Can index Proforma'), ('read_proforma', 'Can read Proforma'))},
        ),
        migrations.AlterField(
            model_name='reqspec',
            name='type',
            field=models.IntegerField(choices=[(0, 'Routine'), (1, 'Project'), (2, 'Services'), (3, 'Ex')], default=0),
        ),
    ]
