# Generated by Django 2.0.2 on 2019-11-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0035_auto_20191113_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.BigIntegerField(default=55005500)),
                ('summary', models.CharField(blank=True, max_length=150, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Requests')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
