# Generated by Django 2.0.2 on 2019-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0036_auto_20190417_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefspec',
            name='code',
            field=models.BigIntegerField(default=99009900),
        ),
    ]
