# Generated by Django 2.0.2 on 2019-11-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0036_wastage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastage',
            old_name='summary',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='wastage',
            old_name='request',
            new_name='req',
        ),
    ]
