# Generated by Django 2.0.2 on 2019-04-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0037_prefspec_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpref',
            name='temp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
