# Generated by Django 2.0.2 on 2018-11-10 05:51

from django.db import migrations, models
import django.db.models.deletion
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0037_auto_20181109_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=request.models.upload_location)),
            ],
        ),
        migrations.RemoveField(
            model_name='requests',
            name='image',
        ),
        migrations.AddField(
            model_name='requestfiles',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Requests'),
        ),
    ]
