# Generated by Django 2.0.2 on 2019-11-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0038_auto_20191119_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefpart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='prefpart',
            name='reqpart_eq',
        ),
        migrations.RemoveField(
            model_name='prefpart',
            name='xpref',
        ),
        migrations.RemoveField(
            model_name='reqpart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='reqpart',
            name='req',
        ),
        migrations.RemoveField(
            model_name='services',
            name='req',
        ),
        migrations.RemoveField(
            model_name='wastage',
            name='req',
        ),
        migrations.DeleteModel(
            name='PrefPart',
        ),
        migrations.DeleteModel(
            name='ReqPart',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Wastage',
        ),
    ]
