# Generated by Django 2.0.2 on 2018-11-10 14:46

from django.db import migrations, models
import django.db.models.deletion
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0038_auto_20181110_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=request.models.upload_location)),
            ],
        ),
        migrations.RemoveField(
            model_name='xpref',
            name='image',
        ),
        migrations.AddField(
            model_name='proffiles',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Xpref'),
        ),
    ]
