# Generated by Django 2.0.2 on 2020-06-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0040_reqpart_services_wastage'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpref',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
