# Generated by Django 2.0.2 on 2019-05-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0040_xpref_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpref',
            name='to_follow',
            field=models.BooleanField(default=False),
        ),
    ]
