# Generated by Django 2.0.2 on 2018-11-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0040_auto_20181111_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentFiels',
            new_name='PaymentFiles',
        ),
    ]
