# Generated by Django 2.0.2 on 2018-11-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0041_auto_20181112_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqspec',
            name='price',
        ),
    ]
