# Generated by Django 2.0.2 on 2020-06-28 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0041_xpref_signed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=600)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_needed', models.BooleanField(default=False)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Xpref')),
            ],
        ),
    ]
