# Generated by Django 2.0.2 on 2019-05-21 08:19

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0042_xpref_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpref',
            name='date_modified',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
