# Generated by Django 2.0.2 on 2018-12-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0044_auto_20181117_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'permissions': (('index_requests', 'can see list of requests'), ('read_requests', 'can read requests'), ('public_requests', 'public in requests'))},
        ),
    ]
