# Generated by Django 2.0.2 on 2019-05-21 08:52

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0044_auto_20190521_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpref',
            name='date_modified',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
