# Generated by Django 2.0.2 on 2019-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0045_auto_20190521_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpref',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
