# Generated by Django 2.0.2 on 2018-12-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0045_auto_20181203_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqspec',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
