# Generated by Django 2.0.2 on 2019-05-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0046_auto_20190521_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='follow_up',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='to_follow',
            field=models.BooleanField(default=False),
        ),
    ]
