# Generated by Django 2.0.2 on 2019-05-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0047_auto_20190522_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpref',
            name='perm_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
