# Generated by Django 2.0.2 on 2018-12-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0047_auto_20181206_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'permissions': (('index_requests', 'can see list of requests'), ('read_requests', 'can read requests'), ('sale_expert', 'can edit own stuff'))},
        ),
    ]
