# Generated by Django 2.0.2 on 2018-12-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0048_auto_20181206_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'permissions': (('index_requests', 'can see list of requests'), ('read_requests', 'can read requests'), ('public_requests', 'public in requests'), ('sale_expert', 'can edit own stuff'))},
        ),
    ]
