# Generated by Django 2.0.2 on 2018-12-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0050_auto_20181206_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
