# Generated by Django 2.0.2 on 2018-12-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0051_auto_20181206_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqspec',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reqspec',
            name='price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reqspec',
            name='tech',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xpref',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
