# Generated by Django 2.0.2 on 2019-05-29 06:56

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0051_comment_date_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_fa',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
