# Generated by Django 2.0.2 on 2019-06-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0053_auto_20190529_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefspec',
            name='recieved',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
