# Generated by Django 2.0.2 on 2019-06-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0054_prefspec_recieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefspec',
            name='recieved',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
