# Generated by Django 2.0.2 on 2019-06-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0055_auto_20190601_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefspec',
            old_name='recieved',
            new_name='received',
        ),
    ]
