# Generated by Django 2.0.2 on 2019-06-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0056_auto_20190601_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='prefspec',
            name='received',
        ),
    ]
