# Generated by Django 2.0.2 on 2019-06-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0057_auto_20190610_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpref',
            name='perm_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
