# Generated by Django 2.0.2 on 2019-06-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0059_auto_20190618_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='xpref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='request.Xpref'),
        ),
    ]
