# Generated by Django 2.0.2 on 2019-07-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0061_auto_20190622_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpref',
            name='number_auto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xpref',
            name='number_td',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
