# Generated by Django 2.0.2 on 2019-07-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0062_auto_20190723_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xpref',
            name='number_auto',
        ),
        migrations.RemoveField(
            model_name='xpref',
            name='number_td',
        ),
    ]
