# Generated by Django 2.0.2 on 2019-07-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0064_auto_20190723_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpref',
            name='number_auto',
            field=models.IntegerField(unique=True),
        ),
    ]
