# Generated by Django 2.0.2 on 2019-07-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0065_auto_20190723_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpm', models.IntegerField()),
                ('pole', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reqspec',
            name='rpm_new',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.DO_NOTHING, to='request.RpmType'),
            preserve_default=False,
        ),
    ]
