# Generated by Django 2.0.2 on 2019-08-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0067_auto_20190802_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PyamentType',
            new_name='PaymentType',
        ),
    ]
