# Generated by Django 2.0.2 on 2019-08-02 10:08

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0069_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_fa',
            field=django_jalali.db.models.jDateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
