# Generated by Django 2.0.2 on 2019-08-02 10:09

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0070_auto_20190802_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_fa',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
