# Generated by Django 2.0.2 on 2020-08-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfeature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
