# Generated by Django 2.0.2 on 2020-08-22 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelation',
            name='parent',
        ),
        migrations.AddField(
            model_name='userrelation',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_parent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
