# Generated by Django 2.0.2 on 2020-08-22 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200822_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_parent', to=settings.AUTH_USER_MODEL),
        ),
    ]
