# Generated by Django 2.0.2 on 2018-10-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motordb',
            name='base_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motordb',
            name='prime_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motordb',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motordb',
            name='voltage',
            field=models.IntegerField(default=380),
        ),
    ]
