# Generated by Django 2.0.2 on 2018-10-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricedb', '0002_auto_20181012_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='motordb',
            name='price_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pricedb.PriceDb'),
            preserve_default=False,
        ),
    ]
