# Generated by Django 2.0.2 on 2019-08-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricedb', '0003_motordb_pub_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motordb',
            name='pub_date2',
        ),
    ]
