# Generated by Django 2.0.2 on 2018-11-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricedb', '0003_motordb_price_set'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motordb',
            options={'permissions': (('view_pricedb', 'can view price database'), ('clean_pricedb', 'can view price database'))},
        ),
    ]
