# Generated by Django 2.0.2 on 2020-11-30 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AluIngot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
                ('name', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CastIron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
                ('name', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuStator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverheadCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ch_number', models.CharField(max_length=16)),
                ('motor_type', models.CharField(max_length=6)),
                ('date_fa', django_jalali.db.models.jDateField(default=django.utils.timezone.now)),
                ('standard_parts', models.IntegerField()),
                ('cost_production', models.IntegerField()),
                ('general_cost', models.IntegerField()),
                ('cost_practical', models.IntegerField()),
                ('alu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost.AluIngot')),
                ('bearing', models.ManyToManyField(to='cost.Bearing')),
                ('cast_iron', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost.CastIron')),
                ('certificate', models.ManyToManyField(to='cost.Certificate')),
                ('cu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost.CuStator')),
                ('overhead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost.OverheadCost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiliconSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Steel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SteelRebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
                ('name', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WageCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qyt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('machine', 'machine'), ('item', 'item')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectcost',
            name='silicon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost.SiliconSheet'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='steel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost.Steel'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='steel_rebar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost.SteelRebar'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='test',
            field=models.ManyToManyField(to='cost.Test'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='wage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost.WageCost'),
        ),
    ]
