# Generated by Django 2.0.2 on 2020-11-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluingot',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='bearing',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='castiron',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='custator',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='overheadcost',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='siliconsheet',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='steel',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='steelrebar',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='wagecost',
            old_name='qyt',
            new_name='qty',
        ),
    ]
