# Generated by Django 2.0.2 on 2019-08-25 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('motordb', '0001_initial'),
        ('pricedb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primecost',
            name='price_db',
        ),
        migrations.RemoveField(
            model_name='salesprice',
            name='price_set',
        ),
        migrations.AlterModelOptions(
            name='motordb',
            options={'permissions': (('index_motordb', 'can view price database'), ('view_motordb', 'can view price database'), ('clean_motordb', 'can view price database'))},
        ),
        migrations.AlterModelOptions(
            name='pricedb',
            options={'permissions': (('index_pricedb', 'can list price dbs'),)},
        ),
        migrations.RemoveField(
            model_name='motordb',
            name='kw',
        ),
        migrations.RemoveField(
            model_name='motordb',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='motordb',
            name='voltage',
        ),
        migrations.AddField(
            model_name='motordb',
            name='motor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motordb.MotorsCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricedb',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pricedb',
            name='date_published_fa',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='PrimeCost',
        ),
        migrations.DeleteModel(
            name='SalesPrice',
        ),
    ]
