# Generated by Django 2.0.2 on 2019-08-25 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricedb', '0002_auto_20190825_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='motordb',
            name='pub_date2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
