# Generated by Django 2.0.2 on 2019-08-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricedb', '0005_auto_20190825_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motordb',
            old_name='code',
            new_name='motor',
        ),
    ]
